# Generated by Django 6.0.5 on 2026-07-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(blank=True, help_text='Hora de llegada (HH:MM:SS)', null=True)),
                ('departure_time', models.TimeField(blank=True, help_text='Hora de salida (HH:MM:SS)', null=True)),
                ('stop_sequence', models.PositiveIntegerField(help_text='Orden de la parada en este viaje (1, 2, 3...)')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_parada', to='routes_map.parada')),
            ],
            options={
                'ordering': ['stop_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('direction_id', models.IntegerField(choices=[(0, 'Ida'), (1, 'Vuelta')], default=0, help_text='0 para Ida, 1 para Vuelta (Estándar GTFS)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='routes_map.ruta')),
            ],
        ),
    ]
