# Generated by Django 6.0.5 on 2026-05-31 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_map', '0001_initial'),
        ('transit_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('direction_id', models.IntegerField(choices=[(0, 'Ida'), (1, 'Vuelta')], default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='routes_map.ruta')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transit_general.calendario')),
            ],
        ),
        migrations.CreateModel(
            name='TiempoParada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(help_text='Hora de llegada (HH:MM:SS)')),
                ('departure_time', models.TimeField(help_text='Hora de salida (HH:MM:SS)')),
                ('stop_sequence', models.IntegerField(help_text='Orden de la parada en este viaje (1, 2, 3...)')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_parada', to='routes_map.parada')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_parada', to='scheduler.viaje')),
            ],
            options={
                'unique_together': {('trip', 'stop_sequence')},
            },
        ),
    ]
