# Generated by Django 6.0.5 on 2026-07-28 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_map', '0002_initial'),
        ('scheduler', '0001_initial'),
        ('transit_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transit_general.calendario'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='shape',
            field=models.ForeignKey(blank=True, help_text='Trazado geoespacial (shape_id) asociado a este viaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='routes_map.trazadoruta'),
        ),
        migrations.AddField(
            model_name='tiempoparada',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiempos_parada', to='scheduler.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='tiempoparada',
            unique_together={('trip', 'stop_sequence')},
        ),
    ]
