# Generated by Django 6.0.5 on 2026-05-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('agency_id', models.CharField(help_text='ID único de la empresa de transporte', max_length=50, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_url', models.URLField()),
                ('agency_timezone', models.CharField(default='America/Mexico_City', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('service_id', models.CharField(help_text='ID del bloque de días (Ej: LUN-VIE)', max_length=50, primary_key=True, serialize=False)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField(help_text='Fecha de inicio del servicio (YYYY-MM-DD)')),
                ('end_date', models.DateField(help_text='Fecha de fin del servicio (YYYY-MM-DD)')),
            ],
        ),
    ]
