# Generated by Django 6.0.5 on 2026-08-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_map', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('agency_id', models.CharField(help_text='ID único de la empresa/secretaría', max_length=50, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_url', models.URLField(default='https://smyt.gob.mx')),
                ('agency_timezone', models.CharField(default='America/Mexico_City', max_length=50)),
                ('agency_lang', models.CharField(blank=True, default='es', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(blank=True, help_text='Nombre o alias del servicio (Ej: LUN-VIE)', max_length=100, null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField(help_text='Fecha de inicio del servicio (YYYY-MM-DD)')),
                ('end_date', models.DateField(help_text='Fecha de fin del servicio (YYYY-MM-DD)')),
            ],
        ),
        migrations.CreateModel(
            name='TarifaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_id', models.CharField(blank=True, help_text='ID de tarifa GTFS', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=10.0, max_digits=6)),
                ('currency_type', models.CharField(default='MXN', max_length=3)),
                ('payment_method', models.IntegerField(default=0, help_text='0 = Pago a bordo')),
                ('transfers', models.IntegerField(default=0, help_text='0 = No permite transbordos')),
            ],
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Hora de inicio del bloque (HH:MM:SS)')),
                ('end_time', models.TimeField(help_text='Hora de fin del bloque (HH:MM:SS)')),
                ('headway_secs', models.IntegerField(help_text='Intervalo entre salidas en segundos')),
                ('trip', models.ForeignKey(help_text='Viaje asociado a esta frecuencia', on_delete=django.db.models.deletion.CASCADE, related_name='frecuencias', to='scheduler.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='TarifaRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_general.tarifaatributo')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_map.ruta')),
            ],
        ),
    ]
