# Generated by Django 6.0.5 on 2026-06-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes_map', '0001_initial'),
        ('transit_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifaAtributo',
            fields=[
                ('fare_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency_type', models.CharField(default='MXN', max_length=3)),
                ('payment_method', models.IntegerField(default=0)),
                ('transfers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TarifaRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_general.tarifaatributo')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes_map.ruta')),
            ],
        ),
    ]
