"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&n5oxy(xm&^x%wpf1dyjq=b)hbqrst%4d)efw4nba=eczg@pic'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #'django.contrib.gis',
    'rest_framework',             
    'corsheaders',                
    
    
    'apps.transit_general.apps.TransitGeneralConfig',
    'apps.routes_map.apps.RoutesMapConfig',
    'apps.scheduler.apps.SchedulerConfig',
    
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # 👈 ¡Añade esta línea aquí!
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis', 
        'NAME': 'tu_base_datos_gtfs',                       # El nombre que le diste en pgAdmin
        'USER': '',                                 # Tu usuario de Postgres
        'PASSWORD': 'root',                     # Tu contraseña de Postgres
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
CORS_ALLOW_ALL_ORIGINS = True

# core/settings.py (Hasta el final de todo tu archivo)
import os
import sys

OSGEO4W_ROOT = r"C:\OSGeo4W"
OSGEO4W_BIN = os.path.join(OSGEO4W_ROOT, "bin")

# 1. Agregamos la ruta al sistema operativo
os.environ["PATH"] = OSGEO4W_BIN + os.pathsep + os.environ["PATH"]

# 2. ⚡ TRUCO VITAL PARA PYTHON RECIENTE EN WINDOWS ⚡
# Le dice a Python explícitamente que permita cargar dependencias de esta carpeta
if sys.platform == "win32" and hasattr(os, "add_dll_directory"):
    os.add_dll_directory(OSGEO4W_BIN)

# 3. Configuramos las rutas explícitas de GeoDjango
GEOS_LIBRARY_PATH = os.path.join(OSGEO4W_BIN, "geos_c.dll")
GDAL_LIBRARY_PATH = os.path.join(OSGEO4W_BIN, "gdal313.dll") # 👈 Tu archivo exacto
