# Generated by Django 6.0.5 on 2026-08-04 21:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(blank=True, help_text='Folio de parada GTFS', max_length=50, null=True)),
                ('stop_name', models.CharField(max_length=150)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Ubicación geográfica (Punto en PostGIS)', srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, help_text='Folio interno/GTFS (Opcional)', max_length=50, null=True)),
                ('route_short_name', models.CharField(help_text='Ej: R-10 o Combis UTT', max_length=20)),
                ('route_long_name', models.CharField(max_length=150)),
                ('route_type', models.IntegerField(default=3, help_text='3 significa Autobús/Combi en el estándar GTFS')),
            ],
        ),
        migrations.CreateModel(
            name='TrazadoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.CharField(blank=True, help_text='ID del trazado GTFS', max_length=50, null=True)),
                ('direccion', models.IntegerField(choices=[(0, 'Ida'), (1, 'Vuelta')], default=0)),
                ('duracion_estimada_min', models.PositiveIntegerField(default=30, help_text='Duración total del recorrido en minutos.')),
                ('geometria', django.contrib.gis.db.models.fields.LineStringField(help_text='Línea de la ruta (LineString)', srid=4326)),
            ],
        ),
    ]
