# Generated by Django 6.0.5 on 2026-05-31 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transit_general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=150)),
                ('stop_lat', models.FloatField(help_text='Latitud geográfica')),
                ('stop_lon', models.FloatField(help_text='Longitud geográfica')),
            ],
        ),
        migrations.CreateModel(
            name='TrazadoRuta',
            fields=[
                ('shape_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coordenadas_json', models.TextField(help_text='Lista de latitudes y longitudes en formato JSON string')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(help_text='Ej: R-10 o Combis UTT', max_length=20)),
                ('route_long_name', models.CharField(max_length=150)),
                ('route_type', models.IntegerField(default=3, help_text='3 significa Autobús/Combi en el estándar GTFS')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='transit_general.agencia')),
            ],
        ),
    ]
