# Generated by Django 6.0.5 on 2026-08-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes_map', '0001_initial'),
        ('transit_general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='transit_general.agencia'),
        ),
        migrations.AddField(
            model_name='trazadoruta',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trazados', to='routes_map.ruta'),
        ),
    ]
